### ISSUE TITLE
single-step debug

### ISSUE THREAD

**Issue by yhldhit** [zhuhan1236/mmd-caffe#1]
When I uncomment the code DEBUG=1 in file "Makefile.config", there is no problem compiling. However, it returns an error when runing, saying: 
Expr:-CGAL_IA_MUL(-1.1,10.1)!=CGAL_IA_MUL(1.1,10.1)
Explanation:Wrong rounding: did you forget the -frounding-math option if you use GCC (or -f-model strict for Intel)
 I cannot find a solution and can you give me some advices? Thank you.

**Comment by zhuhan1236** [comment]
I am sorry that I've never uncommented DEBUG=1. So, I have no idea what actually happened. But according to the ERROR MESSAGE, maybe there's something wrong with CGAL?

**Comment by yhldhit** [comment]
Ok，thank you all the same~ 发自网易邮箱大师 On 2016-06-04 21:09 , zhuhan1236 Wrote: I am sorry that I've never uncommented DEBUG=1. So, I have no idea what actually happened. But according to the ERROR MESSAGE, maybe there's something wrong with CGAL? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yhldhit** [comment]
Thank you @zhuhan1236. It comes out that there is indeed something wrong with CGAL. When I compile the project adding -DCGAL_DISABLE_ROUNDING_MATH_CHECK in variable named NVCCFLAGS in Makefile, I can normally debug this project. But I got a new problem that I am not able to reproduce the  results given in the paper. When I deal with the task amazon to  webcame, the average in my experiment around 65%, not 68% in the paper. So I will appreciate if you can provide me some suggestions,

**Comment by zhuhan1236** [comment]
Thank you for fixing it. Which model did you run? The `icml` one or the `alex_net` one?

**Comment by yhldhit** [comment]
It's my pleasure. And I did experiments on icml model

**Comment by zhuhan1236** [comment]
Did you use the sub-sampling dataset or the full dataset of amazon to webcam?

**Comment by yhldhit** [comment]
I tested on both dataset. And got almost the same result. In addition, a new problem confused me: I firstly borrowed the weights from bvlc. After that, should I fine tune the weights in conv3 to conv5 before training or, instead, directly start training? Thanks. 发自网易邮箱大师 On 2016-06-07 11:03 , zhuhan1236 Wrote: Did you use the sub-sampling dataset or the full dataset of amazon to webcam? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zhuhan1236** [comment]
Have you tried to tune the hyper-parameter `mmd_lambda`? You can directly start training.

**Comment by yhldhit** [comment]
@zhuhan1236  I used the parameters given in this code and I will try to fine-tune the hyper-parameter in the following experiments thanks to your advice. One more question, the office dataset I downloaded contains only 4110 samples, which is different from 4652 described in the paper. Have you encountered the same problem?

**Comment by zhuhan1236** [comment]
Our office dataset contains 4110 samples, too. There may be something wrong when writing the paper. And I'll also tune the parameters after these busy days.

**Comment by yhldhit** [comment]
@zhuhan1236 Thanks for your time~

**Comment by yhldhit** [comment]
Hi zhuhan
    How are you? I discussed with you on Github about the projected
mmd-caffe and you did give me some useful advice. I have recently conducted
some new experiments based on your implemention. But I have encountered
some other problems. One of the problems is that I can reproduce the
experimental results stated in the paper without given the detailed
experiment setting. Can you offer me more information about this.
  BTW, do you mind to invite me as your  QQ contacts(my QQ number is
1154761720), so that I can contact you easier and we can discuss on the
topic of domain adaption in the future.
 Thanks for your time.

2016-06-14 9:55 GMT+08:00 zhuhan1236 notifications@github.com:

**Comment by zhuhan1236** [comment]
OK, I've invited you in QQ

**Comment by yhldhit** [comment]
Sorry, it seems that I missed your inviting message for some reason. Could you please invite me once again. Thanks~ 发自网易邮箱大师 On 2016-08-30 10:28 , zhuhan1236 Wrote: OK, I've invited you in QQ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.
