### ISSUE TITLE
 Aborted at 1478502296 (unix time) try "date -d @1478502296" if you are using GNU date ***

### ISSUE THREAD

**Issue by ZhuangNi** [zhuhan1236/mmd-caffe#3]
Hi,zhuhan.When I added your implemention of MMD to the lastest caffe version,I met the following error:
`*** Aborted at 1478502296 (unix time) try "date -d @1478502296" if you are using GNU date ***
PC: @     0x7f645ee615a6 caffe::Blob<>::Reshape()
*** SIGSEGV (@0x0) received by PID 21540 (TID 0x7f645f8b9a40) from PID 0; stack trace: ***
    @     0x7f645d7d5cb0 (unknown)
    @     0x7f645ee615a6 caffe::Blob<>::Reshape()
    @     0x7f645edf645a caffe::Net<>::ForwardFromTo()
    @     0x7f645edf67f7 caffe::Net<>::Forward()
    @     0x7f645ee52807 caffe::Solver<>::Step()
    @     0x7f645ee530c9 caffe::Solver<>::Solve()
    @           0x4094ab train()
    @           0x4068ac main
    @     0x7f645d7c0f45 (unknown)
    @           0x40711b (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)`
 It works well before the program run `if(now_iter_>=iter_of_epoch) ,..,blablabla` command.
Could you tell me what happens?
Thanks in advance.

**Comment by zhuhan1236** [comment]
Just as I said in #2 , the implementation is not elegant and I modified a lot of original caffe layers like data_layer, softmax_loss_layer and so on. So, the correctness of mmd_layer depends on the whole mmd-caffe project. If you want to run this code, you should clone and compile the complete project. And I'am going to publish a simplified and independent 'mmd_layer' in a few days.

**Comment by ZhuangNi** [comment]
Thank you very much! I just use the latest MMD implemention ,and it could work.

**Comment by zhuhan1236** [comment]
You mean the latest master branch? It does work but a bit inconvenient for users...

**Comment by ZhuangNi** [comment]
I added the MMD Loss to the latest caffe version and use it to train my own data, but the accuracy is just  0.5675. It just start train.

**Comment by ZhuangNi** [comment]
Anyway, thank you very much! I will find the other bug of the program .

**Comment by zhuhan1236** [comment]
Please move to [transfer-caffe](https://github.com/zhuhan1236/transfer-caffe)

**Comment by ZhuangNi** [comment]
OK! You are so nice! Thank you very much!

**Comment by zhuhan1236** [comment]
That's fine.
